
// Medical condition aliases and abbreviations mapping - Expanded version
export const DISEASE_ALIAS_MAP: Record<string, string> = {
  // Viral infections
  "hiv": "HIV/AIDS",
  "aids": "HIV/AIDS",
  "covid": "COVID-19",
  "covid-19": "COVID-19",
  "coronavirus": "COVID-19",
  "flu": "Influenza",
  "influenza": "Influenza",
  "hep": "Hepatitis",
  "hep a": "Hepatitis A",
  "hep b": "Hepatitis B",
  "hep c": "Hepatitis C",
  "hepatitis": "Hepatitis",
  "cmv": "Cytomegalovirus",
  "mono": "Mononucleosis",
  "hsv": "Herpes Simplex Virus",
  "herpes": "Herpes Simplex Virus",
  
  // Bacterial infections
  "tb": "Tuberculosis",
  "tuberculosis": "Tuberculosis",
  "strep": "Streptococcal Infection",
  "strep throat": "Streptococcal Pharyngitis",
  "pneumonia": "Pneumonia",
  "staph": "Staphylococcal Infection",
  "mrsa": "Methicillin-resistant Staphylococcus aureus",
  "uti": "Urinary Tract Infection",
  "bladder infection": "Urinary Tract Infection",
  "kidney infection": "Pyelonephritis",
  
  // Digestive conditions
  "ulcer": "Peptic Ulcer Disease",
  "ulcers": "Peptic Ulcer Disease",
  "peptic ulcer": "Peptic Ulcer Disease",
  "stomach ulcer": "Peptic Ulcer Disease",
  "gerd": "Gastroesophageal Reflux Disease",
  "acid reflux": "Gastroesophageal Reflux Disease",
  "heartburn": "Gastroesophageal Reflux Disease",
  "ibs": "Irritable Bowel Syndrome",
  "crohn's": "Crohn's Disease",
  "crohns": "Crohn's Disease",
  "uc": "Ulcerative Colitis",
  "colitis": "Ulcerative Colitis",
  "celiac": "Celiac Disease",
  "gastritis": "Gastritis",
  "diverticulitis": "Diverticulitis",
  
  // Cardiovascular conditions
  "bp": "Hypertension",
  "high blood pressure": "Hypertension",
  "hypertension": "Hypertension",
  "htn": "Hypertension",
  "heart attack": "Myocardial Infarction",
  "mi": "Myocardial Infarction",
  "heart failure": "Congestive Heart Failure",
  "chf": "Congestive Heart Failure",
  "stroke": "Cerebrovascular Accident",
  "cva": "Cerebrovascular Accident",
  "afib": "Atrial Fibrillation",
  "a-fib": "Atrial Fibrillation",
  "mvp": "Mitral Valve Prolapse",
  "cad": "Coronary Artery Disease",
  "pad": "Peripheral Artery Disease",
  "dvt": "Deep Vein Thrombosis",
  "pe": "Pulmonary Embolism",
  "high cholesterol": "Hypercholesterolemia",
  
  // Endocrine conditions
  "diabetes": "Diabetes Mellitus",
  "type 1": "Diabetes Mellitus Type 1",
  "type 2": "Diabetes Mellitus Type 2",
  "t1d": "Diabetes Mellitus Type 1",
  "t2d": "Diabetes Mellitus Type 2",
  "type 1 diabetes": "Diabetes Mellitus Type 1",
  "type 2 diabetes": "Diabetes Mellitus Type 2",
  "thyroid": "Thyroid Disease",
  "hypothyroidism": "Hypothyroidism",
  "hyperthyroidism": "Hyperthyroidism",
  "graves": "Graves' Disease",
  "hashimoto's": "Hashimoto's Thyroiditis",
  "hashimotos": "Hashimoto's Thyroiditis",
  "pcos": "Polycystic Ovary Syndrome",
  "cushings": "Cushing's Syndrome",
  "cushing's": "Cushing's Syndrome",
  "addison's": "Addison's Disease",
  "addisons": "Addison's Disease",
  
  // Respiratory conditions
  "copd": "Chronic Obstructive Pulmonary Disease",
  "emphysema": "Emphysema",
  "chronic bronchitis": "Chronic Bronchitis",
  "asthma": "Asthma",
  "cf": "Cystic Fibrosis",
  "cystic fibrosis": "Cystic Fibrosis",
  "sleep apnea": "Sleep Apnea",
  "osa": "Obstructive Sleep Apnea",
  "pulmonary fibrosis": "Pulmonary Fibrosis",
  "bronchitis": "Bronchitis",
  
  // Cancer
  "cancer": "Cancer",
  "ca": "Cancer",
  "carcinoma": "Carcinoma",
  "sarcoma": "Sarcoma",
  "leukemia": "Leukemia",
  "lymphoma": "Lymphoma",
  "melanoma": "Melanoma",
  "aml": "Acute Myeloid Leukemia",
  "all": "Acute Lymphoblastic Leukemia",
  "cll": "Chronic Lymphocytic Leukemia",
  "cml": "Chronic Myeloid Leukemia",
  "nhl": "Non-Hodgkin Lymphoma",
  "hl": "Hodgkin Lymphoma",
  "basal cell": "Basal Cell Carcinoma",
  "squamous cell": "Squamous Cell Carcinoma",
  
  // Neurological conditions
  "ms": "Multiple Sclerosis",
  "multiple sclerosis": "Multiple Sclerosis",
  "als": "Amyotrophic Lateral Sclerosis",
  "lou gehrig's": "Amyotrophic Lateral Sclerosis",
  "parkinson's": "Parkinson's Disease",
  "parkinsons": "Parkinson's Disease",
  "pd": "Parkinson's Disease",
  "alzheimer's": "Alzheimer's Disease",
  "alzheimers": "Alzheimer's Disease",
  "ad": "Alzheimer's Disease",
  "dementia": "Dementia",
  "epilepsy": "Epilepsy",
  "seizure disorder": "Epilepsy",
  "migraine": "Migraine",
  "migraines": "Migraine",
  "tbi": "Traumatic Brain Injury",
  "concussion": "Concussion",
  
  // Mental health conditions
  "depression": "Major Depressive Disorder",
  "mdd": "Major Depressive Disorder",
  "anxiety": "Anxiety Disorder",
  "gad": "Generalized Anxiety Disorder",
  "panic": "Panic Disorder",
  "ocd": "Obsessive-Compulsive Disorder",
  "ptsd": "Post-Traumatic Stress Disorder",
  "bipolar": "Bipolar Disorder",
  "bd": "Bipolar Disorder",
  "schizophrenia": "Schizophrenia",
  "eating disorder": "Eating Disorder",
  "anorexia": "Anorexia Nervosa",
  "bulimia": "Bulimia Nervosa",
  "binge eating": "Binge Eating Disorder",
  "adhd": "Attention-Deficit/Hyperactivity Disorder",
  "add": "Attention-Deficit Disorder",
  
  // Musculoskeletal conditions
  "arthritis": "Arthritis",
  "osteoarthritis": "Osteoarthritis",
  "oa": "Osteoarthritis",
  "rheumatoid arthritis": "Rheumatoid Arthritis",
  "ra": "Rheumatoid Arthritis",
  "lupus": "Systemic Lupus Erythematosus",
  "sle": "Systemic Lupus Erythematosus",
  "fibromyalgia": "Fibromyalgia",
  "fibro": "Fibromyalgia",
  "osteoporosis": "Osteoporosis",
  "gout": "Gout",
  "tendonitis": "Tendonitis",
  "carpal tunnel": "Carpal Tunnel Syndrome",
  "cts": "Carpal Tunnel Syndrome",
  "herniated disc": "Herniated Disc",
  "herniated disk": "Herniated Disc",
  "sciatica": "Sciatica",
  "back pain": "Back Pain",
  
  // Dermatological conditions
  "eczema": "Eczema",
  "psoriasis": "Psoriasis",
  "rosacea": "Rosacea",
  "acne": "Acne",
  "dermatitis": "Dermatitis",
  "shingles": "Shingles",
  "herpes zoster": "Shingles",
  
  // Urology/Sexual health
  "ed": "Erectile Dysfunction",
  "bph": "Benign Prostatic Hyperplasia",
  "enlarged prostate": "Benign Prostatic Hyperplasia",
  "prostatitis": "Prostatitis",
  "uti": "Urinary Tract Infection",
  "incontinence": "Urinary Incontinence",
  "kidney stones": "Nephrolithiasis",
  "ckd": "Chronic Kidney Disease",
  "kidney disease": "Chronic Kidney Disease",
  "esrd": "End-Stage Renal Disease",
  "std": "Sexually Transmitted Disease",
  "sti": "Sexually Transmitted Infection",
  
  // Women's health
  "pcos": "Polycystic Ovary Syndrome",
  "endometriosis": "Endometriosis",
  "endo": "Endometriosis",
  "fibroids": "Uterine Fibroids",
  "pms": "Premenstrual Syndrome",
  "pmdd": "Premenstrual Dysphoric Disorder",
  "menopause": "Menopause",
  "perimenopause": "Perimenopause",
  
  // Common symptoms
  "headache": "Headache",
  "headaches": "Headache",
  "fatigue": "Fatigue",
  "tiredness": "Fatigue",
  "insomnia": "Insomnia",
  "sleeplessness": "Insomnia",
  "sleep trouble": "Insomnia",
  "cough": "Cough",
  "sore throat": "Pharyngitis",
  "fever": "Fever",
  "nausea": "Nausea",
  "vomiting": "Vomiting",
  "diarrhea": "Diarrhea",
  "constipation": "Constipation",
  "dizziness": "Dizziness",
  "vertigo": "Vertigo",
  "rash": "Rash",
  "itching": "Pruritus",
};

// List of common symptoms for validation
export const MEDICAL_SYMPTOMS = [
  // Common symptoms (expanded)
  "fever", "cough", "headache", "pain", "nausea", "vomiting", "diarrhea", 
  "fatigue", "weakness", "dizziness", "rash", "swelling", "bleeding", "bruising",
  "shortness of breath", "chest pain", "abdominal pain", "joint pain", "muscle pain",
  "sore throat", "runny nose", "congestion", "itching", "burning", "numbness",
  "tingling", "stiffness", "tremor", "seizure", "confusion", "memory loss", "insomnia",
  "sneezing", "wheezing", "hoarseness", "loss of appetite", "weight loss", "weight gain",
  "thirst", "frequent urination", "blood in urine", "blood in stool", "black stool",
  "yellow skin", "yellow eyes", "blurry vision", "double vision", "hearing loss",
  "ringing in ears", "loss of taste", "loss of smell", "difficulty swallowing",
  "difficulty breathing", "fast heartbeat", "irregular heartbeat", "slow heartbeat",
  "high blood pressure", "low blood pressure", "sweating", "chills", "hot flashes",
  "night sweats", "swollen glands", "swollen legs", "swollen ankles", "dry mouth",
  "dry eyes", "dry skin", "excessive drooling", "snoring", "hair loss", "brittle nails",
  "brittle hair", "muscle cramps", "muscle weakness", "joint stiffness", "back pain",
  "neck pain", "shoulder pain", "knee pain", "ankle pain", "wrist pain", "foot pain",
  "hand pain", "stomach pain", "abdominal cramps", "rectal pain", "genital pain",
  "testicular pain", "pelvic pain", "menstrual pain", "painful urination", "frequent urination",
  "urgent urination", "difficulty urinating", "blood in semen", "erectile dysfunction",
  "premature ejaculation", "vaginal discharge", "vaginal dryness", "vaginal itching",
  "vaginal odor", "breast pain", "breast lump", "breast discharge", "nipple discharge",
  "missed period", "irregular periods", "heavy periods", "light periods", "painful periods",
  
  // Mental health symptoms (expanded)
  "anxiety", "depression", "panic", "stress", "mood swings", "hallucinations",
  "delusions", "paranoia", "suicidal thoughts", "racing thoughts", "obsessive thoughts",
  "compulsive behaviors", "flashbacks", "nightmares", "hyperactivity", "irritability",
  "anger", "aggression", "social withdrawal", "isolation", "fear", "phobia", "worry",
  "rumination", "hopelessness", "worthlessness", "guilt", "grief", "emotional numbness",
  "emotional instability", "mania", "euphoria", "grandiosity", "hyperarousal", "hypersexuality",
  
  // Digestive symptoms (expanded)
  "bloating", "constipation", "heartburn", "indigestion", "acid reflux",
  "gas", "belching", "flatulence", "abdominal distension", "stomach cramps",
  "intestinal cramps", "bowel irregularity", "changes in bowel habits", "early satiety",
  "difficulty swallowing", "painful swallowing", "food getting stuck", "regurgitation",
  "bitter taste in mouth", "fecal incontinence", "rectal bleeding", "anal itching",
  "anal pain", "hemorrhoids", "rectal prolapse", "jaundice", "pale stool", "greasy stool",
  "floating stool", "mucus in stool",
  
  // Respiratory symptoms (expanded)
  "wheezing", "breathing difficulty", "sneezing", "coughing up blood",
  "shortness of breath", "shallow breathing", "rapid breathing", "chest tightness",
  "chest congestion", "nasal congestion", "runny nose", "postnasal drip", "stuffy nose",
  "nasal discharge", "sinus pressure", "sinus pain", "sinus congestion", "phlegm",
  "mucus", "coughing up mucus", "dry cough", "wet cough", "productive cough",
  "barking cough", "whooping cough", "croup", "stridor", "hoarseness", "loss of voice",
  
  // Neurological symptoms (expanded)
  "migraine", "dizziness", "vertigo", "tremors", "seizures", "paralysis",
  "weakness", "numbness", "tingling", "paresthesia", "loss of sensation",
  "hypersensitivity", "burning sensation", "electric shock sensation", "pins and needles",
  "coordination problems", "balance problems", "gait disturbance", "difficulty walking",
  "difficulty standing", "difficulty sitting", "difficulty lying down", "fainting",
  "syncope", "loss of consciousness", "altered consciousness", "confusion", "disorientation",
  "memory loss", "forgetfulness", "difficulty concentrating", "brain fog", "slurred speech",
  "speech difficulties", "word-finding difficulties", "facial drooping", "facial numbness",
  "facial weakness", "vision changes", "blind spots", "visual aura", "floaters", "flashes",
  
  // Skin symptoms (expanded)
  "acne", "eczema", "hives", "psoriasis", "dry skin", "itching",
  "rash", "mole changes", "skin discoloration", "redness", "pallor", "cyanosis",
  "jaundice", "flushing", "bruising", "petechiae", "purpura", "skin lesions",
  "skin growths", "skin tags", "warts", "calluses", "corns", "blisters", "boils",
  "cysts", "abscesses", "cellulitis", "dermatitis", "dandruff", "seborrheic dermatitis",
  "contact dermatitis", "atopic dermatitis", "skin peeling", "skin flaking", "scaly skin",
  "skin cracking", "skin bleeding", "excessive sweating", "hyperhidrosis", "night sweats",
  "cold sweats", "hot flashes", "heat intolerance", "cold intolerance", "hair loss",
  "alopecia", "hirsutism", "excessive hair growth", "changes in hair texture",
  "changes in hair color", "brittle nails", "nail discoloration", "nail ridges",
  "nail pitting", "nail separation", "ingrown nails", "fungal nails"
];

// List of medical specialties and systems (expanded)
export const MEDICAL_SPECIALTIES = [
  // Core medical specialties
  "cardiology", "neurology", "psychiatry", "dermatology", "gastroenterology",
  "endocrinology", "rheumatology", "oncology", "pediatrics", "geriatrics",
  "orthopedics", "urology", "gynecology", "obstetrics", "ophthalmology", 
  "otolaryngology", "ent", "pulmonology", "nephrology", "immunology", 
  "hematology", "infectious disease",
  
  // Additional specialties
  "allergy", "anesthesiology", "bariatrics", "colorectal surgery",
  "critical care", "emergency medicine", "family medicine", "general practice",
  "general surgery", "genetics", "hepatology", "internal medicine",
  "neonatology", "neurosurgery", "nuclear medicine", "occupational medicine",
  "pain management", "palliative care", "pathology", "physical medicine",
  "plastic surgery", "preventive medicine", "proctology", "radiology",
  "rehabilitation", "sleep medicine", "sports medicine", "thoracic surgery",
  "transplant surgery", "trauma surgery", "vascular surgery",
  
  // Allied health fields
  "audiology", "chiropractic", "dentistry", "dietetics", "midwifery",
  "nursing", "nutrition", "occupational therapy", "optometry", "pharmacy",
  "physical therapy", "physiotherapy", "podiatry", "psychology",
  "radiography", "respiratory therapy", "speech therapy",
  
  // Alternative and complementary medicine
  "acupuncture", "ayurveda", "herbal medicine", "homeopathy",
  "naturopathy", "traditional chinese medicine"
];
