
// This is a comprehensive mapping of common medical terms and their aliases
// to standardized medical terminology. This improves the accuracy of the AI's
// responses when users use colloquial or abbreviated terms.

export const diseaseAliasesMap: Record<string, string> = {
  // Cardiovascular
  "heart attack": "Myocardial Infarction",
  "mi": "Myocardial Infarction",
  "heart failure": "Congestive Heart Failure",
  "chf": "Congestive Heart Failure",
  "high blood pressure": "Hypertension",
  "htn": "Hypertension",
  "high bp": "Hypertension",
  "afib": "Atrial Fibrillation",
  "a-fib": "Atrial Fibrillation",
  "heart arrhythmia": "Cardiac Arrhythmia",
  "stroke": "Cerebrovascular Accident",
  "cva": "Cerebrovascular Accident",
  "mini stroke": "Transient Ischemic Attack",
  "tia": "Transient Ischemic Attack",
  "pad": "Peripheral Artery Disease",
  "dvt": "Deep Vein Thrombosis",
  "blood clot": "Thrombosis",
  "high cholesterol": "Hypercholesterolemia",
  "artery disease": "Coronary Artery Disease",
  "cad": "Coronary Artery Disease",
  
  // Respiratory
  "copd": "Chronic Obstructive Pulmonary Disease",
  "emphysema": "Emphysema",
  "bronchitis": "Bronchitis",
  "pneumonia": "Pneumonia",
  "asthma": "Asthma",
  "pulmonary fibrosis": "Pulmonary Fibrosis",
  "lung disease": "Pulmonary Disease",
  "tb": "Tuberculosis",
  "sleep apnea": "Obstructive Sleep Apnea",
  "osa": "Obstructive Sleep Apnea",
  "pulmonary embolism": "Pulmonary Embolism",
  "pe": "Pulmonary Embolism",
  "ards": "Acute Respiratory Distress Syndrome",
  "pleural effusion": "Pleural Effusion",
  "cystic fibrosis": "Cystic Fibrosis",
  "cf": "Cystic Fibrosis",
  "covid": "COVID-19",
  "coronavirus": "COVID-19",
  
  // Gastrointestinal
  "gerd": "Gastroesophageal Reflux Disease",
  "acid reflux": "Gastroesophageal Reflux Disease",
  "heartburn": "Pyrosis",
  "peptic ulcer": "Peptic Ulcer Disease",
  "ulcer": "Peptic Ulcer Disease",
  "ibs": "Irritable Bowel Syndrome",
  "inflammatory bowel": "Inflammatory Bowel Disease",
  "ibd": "Inflammatory Bowel Disease",
  "crohn's": "Crohn's Disease",
  "crohns": "Crohn's Disease",
  "ulcerative colitis": "Ulcerative Colitis",
  "uc": "Ulcerative Colitis",
  "celiac": "Celiac Disease",
  "diverticulitis": "Diverticulitis",
  "diverticulosis": "Diverticulosis",
  "gallstones": "Cholelithiasis",
  "pancreatitis": "Pancreatitis",
  "fatty liver": "Non-alcoholic Fatty Liver Disease",
  "nafld": "Non-alcoholic Fatty Liver Disease",
  "hepatitis": "Hepatitis",
  "hep": "Hepatitis",
  "cirrhosis": "Cirrhosis",
  "appendicitis": "Appendicitis",
  "constipation": "Constipation",
  "diarrhea": "Diarrhea",
  
  // Endocrine
  "diabetes": "Diabetes Mellitus",
  "dm": "Diabetes Mellitus",
  "type 1 diabetes": "Type 1 Diabetes Mellitus",
  "type 2 diabetes": "Type 2 Diabetes Mellitus",
  "t1dm": "Type 1 Diabetes Mellitus",
  "t2dm": "Type 2 Diabetes Mellitus",
  "hypothyroidism": "Hypothyroidism",
  "hyperthyroidism": "Hyperthyroidism",
  "thyroid disease": "Thyroid Disease",
  "graves": "Graves' Disease",
  "hashimoto's": "Hashimoto's Thyroiditis",
  "hashimotos": "Hashimoto's Thyroiditis",
  "cushings": "Cushing's Syndrome",
  "cushing's": "Cushing's Syndrome",
  "addison's": "Addison's Disease",
  "addisons": "Addison's Disease",
  "adrenal insufficiency": "Adrenal Insufficiency",
  "cushing disease": "Cushing's Disease",
  "hyperparathyroidism": "Hyperparathyroidism",
  "hypoparathyroidism": "Hypoparathyroidism",
  "acromegaly": "Acromegaly",
  "gout": "Gout",
  "hypoglycemia": "Hypoglycemia",
  "low blood sugar": "Hypoglycemia",
  
  // Neurological
  "alzheimer's": "Alzheimer's Disease",
  "alzheimers": "Alzheimer's Disease",
  "dementia": "Dementia",
  "parkinson's": "Parkinson's Disease",
  "parkinsons": "Parkinson's Disease",
  "ms": "Multiple Sclerosis",
  "multiple sclerosis": "Multiple Sclerosis",
  "epilepsy": "Epilepsy",
  "seizure disorder": "Epilepsy",
  "seizures": "Seizure Disorder",
  "migraine": "Migraine",
  "migraine headache": "Migraine",
  "cluster headache": "Cluster Headache",
  "tension headache": "Tension Headache",
  "concussion": "Concussion",
  "tbi": "Traumatic Brain Injury",
  "brain injury": "Traumatic Brain Injury",
  "meningitis": "Meningitis",
  "encephalitis": "Encephalitis",
  "guillain-barré": "Guillain-Barré Syndrome",
  "guillain barre": "Guillain-Barré Syndrome",
  "myasthenia gravis": "Myasthenia Gravis",
  "bell's palsy": "Bell's Palsy",
  "bells palsy": "Bell's Palsy",
  "neuropathy": "Peripheral Neuropathy",
  "peripheral neuropathy": "Peripheral Neuropathy",
  "als": "Amyotrophic Lateral Sclerosis",
  "lou gehrig's": "Amyotrophic Lateral Sclerosis",
  "huntington's": "Huntington's Disease",
  "huntingtons": "Huntington's Disease",
  "cerebral palsy": "Cerebral Palsy",
  "restless leg": "Restless Leg Syndrome",
  "rls": "Restless Leg Syndrome",
  "narcolepsy": "Narcolepsy",
  "vertigo": "Vertigo",
  "tremor": "Essential Tremor",
  
  // Musculoskeletal
  "arthritis": "Arthritis",
  "osteoarthritis": "Osteoarthritis",
  "oa": "Osteoarthritis",
  "rheumatoid arthritis": "Rheumatoid Arthritis",
  "ra": "Rheumatoid Arthritis",
  "lupus": "Systemic Lupus Erythematosus",
  "sle": "Systemic Lupus Erythematosus",
  "fibromyalgia": "Fibromyalgia",
  "ankylosing spondylitis": "Ankylosing Spondylitis",
  "as": "Ankylosing Spondylitis",
  "psoriatic arthritis": "Psoriatic Arthritis",
  "osteoporosis": "Osteoporosis",
  "herniated disc": "Intervertebral Disc Herniation",
  "slipped disc": "Intervertebral Disc Herniation",
  "scoliosis": "Scoliosis",
  "carpal tunnel": "Carpal Tunnel Syndrome",
  "cts": "Carpal Tunnel Syndrome",
  "tendinitis": "Tendinitis",
  "tendonitis": "Tendinitis",
  "bursitis": "Bursitis",
  "back pain": "Low Back Pain",
  "lumbago": "Low Back Pain",
  "sciatica": "Sciatica",
  "sprain": "Sprain",
  "strain": "Strain",
  "fracture": "Fracture",
  "broken bone": "Fracture",
  "torn meniscus": "Meniscus Tear",
  "acl tear": "Anterior Cruciate Ligament Tear",
  "rotator cuff": "Rotator Cuff Injury",
  "plantar fasciitis": "Plantar Fasciitis",
  "tmj": "Temporomandibular Joint Disorder",
  
  // Infectious Diseases
  "flu": "Influenza",
  "influenza": "Influenza",
  "common cold": "Common Cold",
  "strep throat": "Streptococcal Pharyngitis",
  "hiv": "Human Immunodeficiency Virus",
  "aids": "Acquired Immunodeficiency Syndrome",
  "hiv/aids": "HIV/AIDS",
  "lyme": "Lyme Disease",
  "malaria": "Malaria",
  "hep a": "Hepatitis A",
  "hep b": "Hepatitis B",
  "hep c": "Hepatitis C",
  "herpes": "Herpes Simplex Virus",
  "hsv": "Herpes Simplex Virus",
  "shingles": "Herpes Zoster",
  "mono": "Infectious Mononucleosis",
  "mononucleosis": "Infectious Mononucleosis",
  "ebv": "Epstein-Barr Virus",
  "hpv": "Human Papillomavirus",
  "std": "Sexually Transmitted Disease",
  "sti": "Sexually Transmitted Infection",
  
  // Bacterial infections
  "uti": "Urinary Tract Infection",
  "bladder infection": "Cystitis",
  "cystitis": "Cystitis",
  "mrsa": "Methicillin-resistant Staphylococcus Aureus",
  "c diff": "Clostridioides Difficile",
  "cdiff": "Clostridioides Difficile",
  "e coli": "Escherichia Coli Infection",
  "sepsis": "Sepsis",
  "blood infection": "Sepsis",
  
  // Urological/Nephrological
  "bph": "Benign Prostatic Hyperplasia",
  "enlarged prostate": "Benign Prostatic Hyperplasia",
  "prostatitis": "Prostatitis",
  "urine infection": "Urinary Tract Infection",
  "incontinence": "Urinary Incontinence",
  "kidney stones": "Nephrolithiasis",
  "ckd": "Chronic Kidney Disease",
  "kidney disease": "Chronic Kidney Disease",
  "esrd": "End-Stage Renal Disease",
  "pyelonephritis": "Pyelonephritis",
  
  // Women's health
  "pcos": "Polycystic Ovary Syndrome",
  "endometriosis": "Endometriosis",
  "endo": "Endometriosis",
  "fibroids": "Uterine Fibroids",
  "myoma": "Uterine Fibroids",
  "menopause": "Menopause",
  "perimenopause": "Perimenopause",
  "pms": "Premenstrual Syndrome",
  "pmdd": "Premenstrual Dysphoric Disorder",
  "dysmenorrhea": "Dysmenorrhea",
  "painful periods": "Dysmenorrhea",
  "amenorrhea": "Amenorrhea",
  "missed periods": "Amenorrhea",
  "vaginitis": "Vaginitis",
  "yeast infection": "Vulvovaginal Candidiasis",
  "pid": "Pelvic Inflammatory Disease",
  "bacterial vaginosis": "Bacterial Vaginosis",
  "bv": "Bacterial Vaginosis",
  
  // Mental health
  "depression": "Major Depressive Disorder",
  "mdd": "Major Depressive Disorder",
  "anxiety": "Anxiety Disorder",
  "gad": "Generalized Anxiety Disorder",
  "panic attack": "Panic Disorder",
  "panic disorder": "Panic Disorder",
  "bipolar": "Bipolar Disorder",
  "ocd": "Obsessive-Compulsive Disorder",
  "adhd": "Attention-Deficit/Hyperactivity Disorder",
  "add": "Attention-Deficit/Hyperactivity Disorder",
  "ptsd": "Post-Traumatic Stress Disorder",
  "trauma": "Psychological Trauma",
  "schizophrenia": "Schizophrenia",
  "eating disorder": "Eating Disorder",
  "anorexia": "Anorexia Nervosa",
  "bulimia": "Bulimia Nervosa",
  "binge eating": "Binge Eating Disorder",
  "insomnia": "Insomnia",
  "autism": "Autism Spectrum Disorder",
  "asd": "Autism Spectrum Disorder",
  "personality disorder": "Personality Disorder",
  "borderline": "Borderline Personality Disorder",
  "bpd": "Borderline Personality Disorder",
  
  // Dermatological
  "acne": "Acne Vulgaris",
  "eczema": "Eczema",
  "atopic dermatitis": "Atopic Dermatitis",
  "psoriasis": "Psoriasis",
  "rosacea": "Rosacea",
  "hives": "Urticaria",
  "vitiligo": "Vitiligo",
  "alopecia": "Alopecia",
  "hair loss": "Alopecia",
  "dermatitis": "Dermatitis",
  "skin rash": "Dermatitis",
  "cellulitis": "Cellulitis",
  "melanoma": "Melanoma",
  "skin cancer": "Skin Cancer",
  "impetigo": "Impetigo",
  "cold sore": "Herpes Labialis",
  "warts": "Verruca",
  "fungal infection": "Fungal Skin Infection",
  "ringworm": "Tinea Corporis",
  "athletes foot": "Tinea Pedis",
  "athlete's foot": "Tinea Pedis",
  "scabies": "Scabies",
  
  // Ophthalmological
  "dry eye": "Dry Eye Syndrome",
  "glaucoma": "Glaucoma",
  "cataracts": "Cataract",
  "macular degeneration": "Age-related Macular Degeneration",
  "amd": "Age-related Macular Degeneration",
  "conjunctivitis": "Conjunctivitis",
  "pink eye": "Conjunctivitis",
  "stye": "Hordeolum",
  "retinal detachment": "Retinal Detachment",
  "diabetic retinopathy": "Diabetic Retinopathy",
  "amblyopia": "Amblyopia",
  "lazy eye": "Amblyopia",
  "strabismus": "Strabismus",
  "cross eyed": "Strabismus",
  "presbyopia": "Presbyopia",
  "floaters": "Vitreous Floaters",
  
  // ENT
  "sinusitis": "Sinusitis",
  "sinus infection": "Sinusitis",
  "otitis media": "Otitis Media",
  "ear infection": "Otitis Media",
  "tonsillitis": "Tonsillitis",
  "vertigo": "Vertigo",
  "meniere's": "Meniere's Disease",
  "menieres": "Meniere's Disease",
  "tinnitus": "Tinnitus",
  "ringing ears": "Tinnitus",
  "hearing loss": "Hearing Loss",
  "nosebleed": "Epistaxis",
  "nasal polyps": "Nasal Polyps",
  "deviated septum": "Deviated Nasal Septum",
  "laryngitis": "Laryngitis",
  "sleep apnea": "Obstructive Sleep Apnea",
  
  // Oncological
  "cancer": "Cancer",
  "leukemia": "Leukemia",
  "lymphoma": "Lymphoma",
  "hodgkin's": "Hodgkin's Lymphoma",
  "hodgkins": "Hodgkin's Lymphoma",
  "nhl": "Non-Hodgkin Lymphoma",
  "breast cancer": "Breast Cancer",
  "lung cancer": "Lung Cancer",
  "colon cancer": "Colorectal Cancer",
  "colorectal": "Colorectal Cancer",
  "prostate cancer": "Prostate Cancer",
  "ovarian cancer": "Ovarian Cancer",
  "pancreatic cancer": "Pancreatic Cancer",
  "brain tumor": "Brain Tumor",
  "glioma": "Glioma",
  "glioblastoma": "Glioblastoma",
  "gbm": "Glioblastoma",
  "melanoma": "Melanoma",
  "carcinoma": "Carcinoma",
  "sarcoma": "Sarcoma",
  "metastasis": "Metastatic Cancer",
  "metastatic": "Metastatic Cancer",
  "mets": "Metastatic Cancer",
  
  // Hematological
  "anemia": "Anemia",
  "iron deficiency": "Iron Deficiency Anemia",
  "b12 deficiency": "Vitamin B12 Deficiency",
  "hemochromatosis": "Hemochromatosis",
  "itp": "Immune Thrombocytopenia",
  "thrombocytopenia": "Thrombocytopenia",
  "neutropenia": "Neutropenia",
  "polycythemia": "Polycythemia",
  "hemophilia": "Hemophilia",
  "sickle cell": "Sickle Cell Disease",
  "thalassemia": "Thalassemia"
};

// Medical specialties in proper categories
export const medicalSpecialties = [
  "cardiology", "pulmonology", "gastroenterology", "endocrinology", "neurology",
  "rheumatology", "infectious disease", "urology", "nephrology", "gynecology",
  "obstetrics", "psychiatry", "dermatology", "ophthalmology", "otolaryngology",
  "oncology", "hematology", "pediatrics", "geriatrics", "orthopedics",
  "radiology", "anesthesiology", "emergency medicine", "family medicine",
  "internal medicine", "pathology", "physical therapy", "occupational therapy",
  "naturopathy", "traditional chinese medicine"
];
