
[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*; font-src 'self'; connect-src 'self' https://*.supabase.co https://supabase.co https://api.openai.com https://api.groq.com https://generativelanguage.googleapis.com https://api-inference.huggingface.co https://*.lovable.ai https://*.lovable.app https://*.lovable.dev wss://*.supabase.co; frame-src 'self'; media-src 'self';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
