
[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable cache for development/preview builds
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
  
# For production, cache static assets
[context.production]
  [[headers]]
    for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [[headers]]
    for = "/*.png"
    [headers.values]
      Cache-Control = "public, max-age=3600"

  [[headers]]
    for = "/*.jpg"
    [headers.values]
      Cache-Control = "public, max-age=3600"

# Force HTTPS for all connections
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Clear cache on every deploy
[build.processing.html]
  pretty_urls = true
[build.processing]
  skip_processing = false

# Updated CSP headers to allow all required resources including Supabase connections
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://cdn.gpteng.co; connect-src 'self' https://*.lovable.dev https://generativelanguage.googleapis.com https://*.youtube.com https://*.googleapis.com https://*.supabase.co https://api.groq.com; img-src 'self' data: https://*.ytimg.com https://img.youtube.com https://i.ytimg.com https://*.unsplash.com https://*.googleusercontent.com blob: /lovable-uploads/*; style-src 'self' 'unsafe-inline'; frame-src 'self' https://*.youtube.com https://www.youtube.com; media-src 'self' https://*.youtube.com https://www.youtube.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
