// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmjjyoifprnkeitbklpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptamp5b2lmcHJua2VpdGJrbHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTY4NzEsImV4cCI6MjA2MjI3Mjg3MX0.jVxwjIihd22p9pCGus2Q1XQBrKce8DfPaiPTbHaKB0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);